# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Hossam Barakat
tagline:             'Thoughts about ASP.NET, mobility, and technology.'
description:         ''
url:                 http://www.hossambarakat.net
baseurl:             ''
paginate:            5
paginate_path: "page:num"
disqus_shortname: hossambarakat


# About/contact
author:
  name:              Hossam Barakat
  url:               https://twitter.com/hossambarakat_
  bio:               Software consultant, Specialist in .NET platform, agile practitioner and refactoring addict. Core focuses on ASP.NET, Xamarin, SharePoint, Architecture and Design

# Custom vars
version:             1.0.0

# Gems
gems: [jekyll-paginate]
highlighter: rouge